#version: "3.8"
services:
  mictlanx-router-0:
      image: nachocode/mictlanx:router
      container_name:  mictlanx-router-0
      environment:
        - LOGGER_NAME=mictlanx-router-0
        - LOG_PATH=/log
        - TEZCANALYTICX_FLUSH_TIMEOUT=10s
        - TEZCANALYTICX_BUFFER_SIZE=100
        - TEZCANALYTICX_PATH=/api/v4/events
        - TEZCANALYTICX_PORT=45000
        - TEZCANALYTICX_HOSTNAME=tezcanalyticx-0
        - TEZCANALYTICX_LEVEL=0
        - TEZCANALYTICX_PROTOCOL=http
        - TEZCANALYTICX_ENABLE=0
        - MICTLANX_PEERS=mictlanx-peer-0:mictlanx-peer-0:25000 mictlanx-peer-1:mictlanx-peer-1:25001 mictlanx-peer-2:mictlanx-peer-2:25002
        - MICTLANX_PROCOTOL=http
        - MICTLANX_API_VERSION=4
        - MICTLANX_PEER_HEALER_HEARTBEAT=30sec
        - MICTLANX_GC_HEARTBEAT=60sec
        - MICTLANX_ROUTER_HOST=${MICTLANX_ROUTER_HOST-0.0.0.0}
        - MICTLANX_ROUTER_PORT=${MICTLANX_ROUTER_PORT-60666}
        - MICTLANX_SUMMONER_IP_ADDR=mictlanx-summoner-0
        - MICTLANX_SUMMONER_PORT=15000
      command: uvicorn mictlanxrouter.server:app --host ${MICTLANX_ROUTER_HOST-0.0.0.0} --port ${MICTLANX_ROUTER_PORT-60666}
      ports:
         - ${MICTLANX_ROUTER_PORT-60666}:${MICTLANX_ROUTER_PORT-60666}

      volumes:
        - mictlanx-router-0_logs:/log
      networks:
        - mictlanx
      restart: unless-stopped
      depends_on:
        - mictlanx-peer-0
        - mictlanx-peer-1
  mictlanx-peer-0:
    image: nachocode/mictlanx:peer
    container_name: mictlanx-peer-0
    hostname: mictlanx-peer-0
    ports:
      - 25000:25000
    environment:
      - USER_ID=1001
      - GROUP_ID=1002
      - BIN_NAME=peer
      - NODE_ID=mictlanx-peer-0
      - NODE_PORT=25000
      - IP_ADDRESS=mictlanx-peer-0
      - SERVER_IP_ADDR=0.0.0.0
      - NODE_DISK_CAPACITY=10000000000
      - NODE_MEMORY_CAPACITY=1000000000
      - BASE_PATH=${BASE_PATH-/app/mictlanx}
      - LOCAL_PATH=${BASE_PATH-/app/mictlanx}/local
      - DATA_PATH=${BASE_PATH-/app/mictlanx}/data
      - LOG_PATH=${BASE_PATH-/app/mictlanx}/log
      - WORKERS=2
      - MIN_INTERVAL_TIME=15
      - MAX_INTERVAL_TIME=20
      - PAYLOAD_LIMIT=25600000000
      - CLIENT_REQUEST_TIMEOUT=300
      - CLIENT_DISCONNECT_TIMEOUT=60
      - AGENT_UNIX_SOCKET_PATH=${BASE_PATH-/app/mictlanx}/mictlanx.sock
      - CLEAN_CACHE=false
    volumes:
         - mictlanx-peer-0:/mictlanx
        #- /mictlanx/mictlanx-peer-0/log:/mictlanx/log
        #- /mictlanx/mictlanx-peer-0/local:/mictlanx/local
        #- /mictlanx/mictlanx-peer-0/data:/mictlanx/data
        #- /mictlanx/mictlanx-peer-0/mictlanx.sock:/mictlanx/mictlanx.sock
    networks:
      - mictlanx
  mictlanx-peer-1:
    image: nachocode/mictlanx:peer
    container_name: mictlanx-peer-1
    hostname: mictlanx-peer-1
    ports:
      - 25001:25001
    environment:
      - USER_ID=1001
      - GROUP_ID=1002
      - BIN_NAME=peer
      - NODE_ID=mictlanx-peer-1
      - NODE_PORT=25001
      - IP_ADDRESS=mictlanx-peer-1
      - SERVER_IP_ADDR=0.0.0.0
      - NODE_DISK_CAPACITY=10000000000
      - NODE_MEMORY_CAPACITY=1000000000
      - PEERS=mictlanx-peer-0:25000
      - BASE_PATH=${BASE_PATH-/app/mictlanx}
      - LOCAL_PATH=${BASE_PATH-/app/mictlanx}/local
      - DATA_PATH=${BASE_PATH-/app/mictlanx}/data
      - LOG_PATH=${BASE_PATH-/app/mictlanx}/log
      - WORKERS=2
      - MIN_INTERVAL_TIME=10
      - MAX_INTERVAL_TIME=20
      - PAYLOAD_LIMIT=25600000000
      - CLIENT_REQUEST_TIMEOUT=300
      - CLIENT_DISCONNECT_TIMEOUT=60
      - AGENT_UNIX_SOCKET_PATH=${BASE_PATH-/app/mictlanx}/mictlanx.sock
      - CLEAN_CACHE=false
    volumes:
         - mictlanx-peer-1:/mictlanx
        #- /mictlanx/mictlanx-peer-1/log:/mictlanx/log
        #- /mictlanx/mictlanx-peer-1/local:/mictlanx/local
        #- /mictlanx/mictlanx-peer-1/data:/mictlanx/data
        #- /mictlanx/mictlanx-peer-1/mictlanx.sock:/mictlanx/mictlanx.sock
    networks:
      - mictlanx

  mictlanx-peer-2:
    image: nachocode/mictlanx:peer
    container_name: mictlanx-peer-2
    hostname: mictlanx-peer-2
    # privileged: true
    ports:
      - 25002:25002
    environment:
      - USER_ID=1001
      - GROUP_ID=1002
      - BIN_NAME=peer
      - NODE_ID=mictlanx-peer-2
      - NODE_PORT=25002
      - IP_ADDRESS=mictlanx-peer-2
      - SERVER_IP_ADDR=0.0.0.0
      - NODE_DISK_CAPACITY=10000000000
      - NODE_MEMORY_CAPACITY=1000000000
      - PEERS=mictlanx-peer-0:25000 mictlanx-peer-1:25001
      - BASE_PATH=${BASE_PATH-/app/mictlanx}
      - LOCAL_PATH=${BASE_PATH-/app/mictlanx}/local
      - DATA_PATH=${BASE_PATH-/app/mictlanx}/data
      - LOG_PATH=${BASE_PATH-/app/mictlanx}/log
      - WORKERS=2
      - MIN_INTERVAL_TIME=10
      - MAX_INTERVAL_TIME=20
      - PAYLOAD_LIMIT=25600000000
      - CLIENT_REQUEST_TIMEOUT=300
      - CLIENT_DISCONNECT_TIMEOUT=60
      - AGENT_UNIX_SOCKET_PATH=${BASE_PATH-/app/mictlanx}/mictlanx.sock
      - CLEAN_CACHE=false
    volumes:
        - mictlanx-peer-2:/mictlanx
        #- /mictlanx/mictlanx-peer-2/log:/mictlanx/log
        #- /mictlanx/mictlanx-peer-2/local:/mictlanx/local
        #- /mictlanx/mictlanx-peer-2/data:/mictlanx/data
        #- /mictlanx/mictlanx-peer-2/mictlanx.sock:/mictlanx/mictlanx.sock
    networks:
      - mictlanx

  mictlanx-summoner-0:
    image: nachocode/mictlanx:summoner
    container_name: mictlanx-summoner-0
    hostname: mictlanx-summoner-0
    privileged: true
    ports:
      - 15000:15000
    environment:
      - USER_ID=1001
      - GROUP_ID=1002
      - DOCKER_GID=1001
      - BASE_PATH=${BASE_PATH-/app/mictlanx}
      - BIN_NAME=summoner
      - NODE_ID=mictlanx-summoner-0
      - NODE_PORT=15000
      - IP_ADDRESS=mictlanx-summoner-0
      - SERVER_IP_ADDR=0.0.0.0
      - LOG_PATH=${BASE_PATH-/app/mictlanx}/log
      - LOCAL_PATH=${BASE_PATH-/app/mictlanx}/local
      - DATA_PATH=${BASE_PATH-/app/mictlanx}/data
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - mictlanx-summoner-0:/mictlanx
        #- /mictlanx/mictlanx-summoner-0/log:/mictlanx/log
        #- /mictlanx/mictlanx-summoner-0/local:/mictlanx/local
        #- /mictlanx/mictlanx-summoner-0/data:/mictlanx/data
    networks:
      - mictlanx
     
volumes:
  mictlanx-router-0_logs:
  mictlanx-peer-0:
  mictlanx-peer-1:
  mictlanx-peer-2:
  mictlanx-summoner-0:
networks:
  mictlanx:
    external: true


  


