name: 🐛 Bug Report
description: File a bug report to help us improve.
title: "[bug]: "
labels: ["bug", "triage"]
assignees: []
body:

  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the details below.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug and what you expected to happen.
      placeholder: A bug happened!
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide minimal steps to reproduce the issue.
      placeholder: "1. Run ..., 2. Observe ..."
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      default: 0.1.0
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      multiple: true
      options:
        - Ubuntu/Linux
        - macOS
        - Windows
        - Other

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Paste any relevant logs or stack traces.
      render: s