name: ✨ Feature Request
description: Suggest an idea for this project.
title: "[feature]: "
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea below.
  - type: textarea
    id: description
    attributes:
      label: Feature description
      description: What should the feature do?
      placeholder: "As a user, I want ..."
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Why is this feature useful? What problem does it solve?
      placeholder: "This will help because ..."
