from mictlanxrouter.controllers.peers import PeersController
from mictlanxrouter.controllers.tasks import TasksController
from mictlanxrouter.controllers.buckets import BucketsController
from mictlanxrouter.controllers.cache import CacheController